export const EXPO_PUBLIC_SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL!;

export const EXPO_PUBLIC_SUPABASE_ANON_KEY =
  process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY!;

export const EXPO_PUBLIC_SUPABASE_SERVICE_ROLE_KEY =
  process.env.EXPO_PUBLIC_SUPABASE_SERVICE_ROLE_KEY!;

export const EXPO_PUBLIC_STRIPE_SECRET_KEY =
  process.env.EXPO_PUBLIC_STRIPE_SECRET_KEY!;

export const EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY =
  process.env.EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY!;

export const EXPO_PUBLIC_REVENUECAT_OFFERING_ID =
  process.env.EXPO_PUBLIC_REVENUECAT_OFFERING_ID!;
export const EXPO_PUBLIC_REVENUECAT_API_KEY_IOS =
  process.env.EXPO_PUBLIC_REVENUECAT_API_KEY_IOS!;
export const EXPO_PUBLIC_REVENUECAT_API_KEY_ANDROID =
  process.env.EXPO_PUBLIC_REVENUECAT_API_KEY_ANDROID!;

export const GEMINI_API_KEY = process.env.EXPO_PUBLIC_GEMINI_API_KEY!;
export const GROQ_API_URL = process.env.EXPO_PUBLIC_GROQ_API_URL!;
